apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-scaler
  namespace: {{ .Values.namespace }}
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.ui.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-api-scaler
  namespace: {{ .Values.namespace }}
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.productApi.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-api-scaler
  namespace: {{ .Values.namespace }}
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.orderApi.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}