apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: secret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: compose
